### ISSUE TITLE
Security warnings 

### ISSUE THREAD

**Issue by vivekKodira** [jfrog/bower-art-resolver#30]
Running `npm audit` displays the following warnings in dependencies of this library.

Log:                                                                                

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ bower-art-resolver [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ bower-art-resolver > request > hawk > boom > hoek            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ bower-art-resolver [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ bower-art-resolver > request > hawk > cryptiles > boom >     │
│               │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ bower-art-resolver [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ bower-art-resolver > request > hawk > hoek                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ bower-art-resolver [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ bower-art-resolver > request > hawk > sntp > hoek            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by jorenbroekema** [comment]
I am also blocked by this security issue. The latest version of request does not seem to depend anymore on hawk. https://github.com/request/request/blob/master/CHANGELOG.md#v2870-20180521 They removed it here in 2.87.0 . I will make a PR to bump the version to at least 2.87.0
