### ISSUE TITLE
Add repository to package.json

### ISSUE THREAD

**Issue by claudiocro** [jfrog/bower-art-resolver#5]
To help developers find the source code please add the repository section to `package.json`:

``` json
"repository": {
    "type": "git",
    "url": "https://github.com/JFrogDev/bower-art-resolver.git"
  }
```

**Comment by eyalbe4** [comment]
Will be added to the next release of the resolver. Thanks @claudiocro .

**Comment by eyalbe4** [comment]
@claudiocro, this is now part of 2.0.2 which has just been released.

**Comment by claudiocro** [comment]
thx! https://github.com/JFrogDev/bower-art-resolver/blob/master/package.json#L7
