### ISSUE TITLE
DEPTH_ZERO_SELF_SIGNED_CERT self signed certificate

### ISSUE THREAD

**Issue by pvblicltd** [jfrog/bower-art-resolver#6]
Node v0.12.7 - We can't get resolver to complete a bower install. We think it may be related to this issue with the "request" library https://github.com/request/request/issues/418.

Has anyone else experienced the same problems?

**Comment by huerlisi** [comment]
This could be solved by using the `strictSSL=false` together with the fix in #3. This PR fixes the bower configuration not being passed to the actual request.

**Comment by eyalbe4** [comment]
@pvblicltd,
Can you please approve that version 2.0.2 fixes this issue by using the strictSSL=false as @huerlisi suggested?

**Comment by eyalbe4** [comment]
@pvblicltd,
May we close this issue?

**Comment by eyalbe4** [comment]
@pvblicltd and all, I'm closing this issue for now. Do let us know if you still experience this issue.
