### ISSUE TITLE
does not respect no_proxy environment variable.

### ISSUE THREAD

**Issue by tdietrich513** [jfrog/bower-art-resolver#9]
The version of request that you are using predates when the request team added support for the no_proxy environment variable. As a result, the proxy will be used no-matter what.

**Comment by eyalbe4** [comment]
@tdietrich513, thanks for identifying this!
I've just changed the request dependency version to ~2.53.0 (Bower is currently using 2.53.0). This change is not yet published, but you can install the resolver directly from github.
Can you see if this change resolves the issue?

**Comment by monzonj** [comment]
I'm afraid it does not. I even updated to the latest version request@2.63.0
I run a small script to test only the request package and that works fine with the NO_PROXY setting. 

It is bower-art-resolver who seems not to be using it.

**Comment by monzonj** [comment]
This line is causing the issue:
https://github.com/JFrogDev/bower-art-resolver/blob/master/lib/request.js#L13

There's no much do to, because the request plugin does not allow to pass noProxy.

I've created a pull request to solve that: https://github.com/request/request/pull/1996

Now there are two posibilities here:
- Wait for the pull request to be included and released and update the code to be:

```
    var _request = request.defaults({
        httpsProxy: config.httpsProxy,
        httpProxy: config.proxy,
        noProxy: config.noProxy,
        ca: config.ca.search[0],
        strictSSL: config.strictSsl,
        timeout: config.timeout
    })
```
- Remove the proxy entry in the above code and let the request plugin to resolve it using env variables

**Comment by eyalbe4** [comment]
Thanks for the research and PR @monzonj !
It If you're able to submit a PR for the bower-art-resolver once bower is released with your PR, we'll make sure to release your fix quickly.

**Comment by brunorubin** [comment]
I'm having issues using this package with a server that is currently behind a `HTTP_PROXY`.

Have you guys found any workaround to this?
I've run some tests locally removing the proxy line to let the request plugin evaluate the environment variables but seems that is not working as well.

cheers.

**Comment by eyalbe4** [comment]
@brunorubin, it looks like [this](https://github.com/request/request/pull/1996) PR has not been handled yet. @monzonj suggested to remove the proxy configuration from the bower-art-resolver code and use environment variables to configure the proxy as described in the "Controlling proxy behavior using environment variables" in the [request](https://github.com/request/request) package readme file.
@monzonj, have you been able to test this by removing the code and setting the variables?
If anyone can confirm that this solution solves the issue, we will make this change to the code.

**Comment by brunorubin** [comment]
@eyalbe4 thanks for your reply.
I've run some tests here and was able to test and confirm that the solution provided by @monzonj solves the issue. There are more details in #20
